### ISSUE TITLE
Kebab case support

### ISSUE THREAD

**Issue by openscript** [jacobwgillespie/fast-case#68]
Thank you for this library. We use it in many projects.

We recently had the use case that we need to transform from camelCase to [kebab-case](https://en.wikipedia.org/wiki/Letter_case#Kebab_case). This is useful if you need to generate CSS with its kebab-case from a camelCase based language like JavaScript.

I suggest an optional parameter on `decamelize` and `depascalize`, where you can define the separator character. This way no breaking change is introduced and gives the user the option to achieve kebab-case.

Would you welcome a PR for this?

**Comment by jacobwgillespie** [comment]
Hey, totally, PRs are welcome! 💯

**Comment by jacobwgillespie** [comment]
Now that #71 has merged, this has been released in version `1.7.0` 🎉 

Thank you so much! 🙌

**Comment by openscript** [comment]
Great thank you @jacobwgillespie :)
